spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

  profiles:
    default: development

server:
  address: 0.0.0.0
  port: ${PORT:8080}

sentry:
  dsn: https://7e0d46d979e9381745b4db1ed25561fd@o4509214198857728.ingest.de.sentry.io/4509214202134608
  send-default-pii: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem