spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

  profiles:
    default: development

server:
  address: 0.0.0.0
  port: ${PORT:8080}

sentry:
  dsn: https://cd3994df397c7d6226ca49cb6e89c1dc@o4510001266491392.ingest.de.sentry.io/4510001358962768
  send-default-pii: true
  tracesSampleRate: 1.0

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem